# Mass-translation script
#
# Kai Brooks
# github.com/kaibrooks

# runs the c2rust translation for all the targets listed below

# targets to build for
target=( AFROMINI AG3XF4 AG3XF7 AIKONF4 AIORACERF3 AIR32 AIRBOTF4 AIRBOTF4SD AIRHEROF3 ALIENFLIGHTF1 ALIENFLIGHTF3 ALIENFLIGHTF4 ALIENFLIGHTNGF7 ALIENWHOOPF4 ALIENWHOOPF7 ANYFCF7 ANYFCM7 BEEBRAIN BEEBRAIN_V2D BEEBRAIN_V2F BEEROTORF4 BEESTORM BETAFLIGHTF3 BETAFLIGHTF4 BLUEJAYF4 CC3D CC3D_OPBL CHEBUZZF3 CJMCU CLRACINGF4 CLRACINGF7 COLIBRI COLIBRI_OPBL COLIBRI_RACE CRAZYBEEF3FR CRAZYBEEF3FS CRAZYFLIE2 CRAZYFLIE2BQ DALRCF405 DALRCF722DUAL DOGE DYSF4PRO EACHIF3 ELLE0 EXUAVF4PRO F4BY FF_ACROWHOOPSP FF_FORTINIF4 FF_FORTINIF4_REV03 FF_KOMBINI FF_PIKOBLX FF_PIKOF4 FF_PIKOF4OSD FF_RADIANCE FISHDRONEF4 FLIP32F3OSD FLYWOOF405 FOXEERF405 FPVM_BETAFLIGHTF7 FRSKYF3 FRSKYF4 FURYF3 FURYF3OSD FURYF4 FURYF4OSD FURYF7 IMPULSERCF3 IRCFUSIONF3 IRCSYNERGYF3 ISHAPEDF3 KAKUTEF4 KAKUTEF4V2 KAKUTEF7 KISSCC KISSFC KISSFCV2F7 KIWIF4 KIWIF4V2 KROOZX LUMBAF3 LUXF4OSD LUXV2_RACE LUX_RACE MATEKF405 MATEKF411 MATEKF411RX MATEKF722 MICROSCISKY MIDELICF3 MLTEMPF4 MLTYPHF4 MOTOLAB MULTIFLITEPICO NAZE NERO NOX NUCLEOF446RE NUCLEOF7 NUCLEOF722 OMNIBUS OMNIBUSF4 OMNIBUSF4FW OMNIBUSF4SD OMNIBUSF7 OMNIBUSF7V2 OMNINXT4 OMNINXT7 PLUMF4 PODIUMF4 PYRODRONEF4 RACEBASE RCEXPLORERF3 REVO REVOLT REVOLTOSD REVONANO REVO_OPBL RG_SSD_F3 RMDO SINGULARITY SIRINFPV SITL SKYZONEF405 SOULF4 SPARKY SPARKY2 SPEEDYBEEF4 SPEKTRUMF400 SPRACINGF3 SPRACINGF3EVO SPRACINGF3MINI SPRACINGF3MQ SPRACINGF3NEO SPRACINGF3OSD SPRACINGF4EVO SPRACINGF4NEO SPRACINGF7DUAL STACKX STM32F3DISCOVERY STM32F4DISCOVERY STM32F7X2 TINYBEEF3 TINYFISH VRRACE WORMFC XRACERF4 X_RACERSPI YUPIF4 YUPIF7 ZCOREF3 )

for i in "${target[@]}"
do
  ./magic.sh $i
done
